### ISSUE TITLE
Update Nestopia UE Flatpak to 1.51.1

### ISSUE THREAD

**Issue by OnRail76** [flathub/ca._0ldsk00l.Nestopia#9]
There is a new pair of updates: “To celebrate the '90s, Nestopia’s Linux port was moved to FLTK and oldschool OpenGL 1.x.” (1.51) and "Nestopia UE 1.51.1 is released. Just a simple point release that fixes a few bugs in the FLTK port and updates to the latest upstream core."  (1,51.1)

With that updates, the emulator goes fullscreen with no problems on any GTK based DE. (Version 1.50 has a lot of problems with that, and seems broken), and stills works perfect under other DE´s, as usual. Hope to see the flatpak updated. Thanks.

**Comment by razzeee** [comment]
Can be closed now

**Comment by OnRail76** [comment]
I totally forgot to close this, sorry! Great workf!
